name: Mobrider
version: '${project.version}'
main: me.notarin.mobrider.Mobrider
api-version: 1.19
authors: [ Notarin ]
description: MOOBRIIDAAAAAAAHHHHHH
commands:
  togglemobriding:
    aliases: ['tglmr']
    description: "toggles mobriding off and on"
